# HYPERION/pyproject.toml

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hyperion_nn"
version = "0.0.0"
dependencies = [
    "numpy>=1.21.0",
    "pandas>=2.0.0",
]

[tool.setuptools.packages.find]
where = ["src/python"]